name: epubx
description: Epub Parser for Dart. Epub package fork. Suitable for use on the Server, the Web, or in Flutter
homepage: https://github.com/SunnatilloShavkatov/epubx.git
issue_tracker: https://github.com/SunnatilloShavkatov/epubx.git
version: 4.0.0
publish_to: https://github.com/SunnatilloShavkatov/epubx.git

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  archive: ^3.6.1
  collection: ^1.18.0
  quiver: ^3.2.1
  path: ^1.9.0
  xml: ^6.5.0
  image: ^4.2.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.25.8
